services:
  postgres:
    image: postgres:16
    container_name: n8n_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  n8n:
    image: n8nio/n8n:1.85.4
    container_name: n8n_app
    restart: unless-stopped
    ports:
      - "5678:5678"        # editor UI
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      # aponta para a pasta de extensões customizadas
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      # volume de dados do n8n (inclui a pasta ~/.n8n)
      - ./data:/home/node/.n8n
      # monta o build do nosso node em /home/node/.n8n/custom/random
      - ./custom-random-node:/home/node/.n8n/custom/random:ro

volumes:
  pgdata:
